In [2]:
import numpy as np
import pandas as pd

In [7]:
w = np.array([4,7,9,1])
m = np.array([[3,2,4,7] , [11,6,7,2]])
print("W:",w)
print("M:",m)
print("W DIM: " , w.ndim)
print("M DIM: " , m.ndim)
print("DTYPE : " , m.dtype)
print("TYPE : ", type(m))

W: [4 7 9 1]
M: [[ 3  2  4  7]
 [11  6  7  2]]
W DIM:  1
M DIM:  2
DTYPE :  int64
TYPE :  <class 'numpy.ndarray'>


In [9]:
print(m)
print("=========================")
print("SHAPE : " , m.shape)

[[ 3  2  4  7]
 [11  6  7  2]]
SHAPE :  (2, 4)


In [10]:
m = np.array([[3,2,4,7] , [11,6,7,2]] , ndmin = 5)
print("M:",m)
print("M DIM: " , m.ndim)

M: [[[[[ 3  2  4  7]
    [11  6  7  2]]]]]
M DIM:  5


In [11]:
m.shape

(1, 1, 1, 2, 4)

In [12]:
m.reshape(8,1)

array([[ 3],
       [ 2],
       [ 4],
       [ 7],
       [11],
       [ 6],
       [ 7],
       [ 2]])

In [13]:
m.reshape(1,8)

array([[ 3,  2,  4,  7, 11,  6,  7,  2]])

In [14]:
m.reshape(8,)

array([ 3,  2,  4,  7, 11,  6,  7,  2])

In [15]:
m.reshape(2,8)

ValueError: cannot reshape array of size 8 into shape (2,8)

In [17]:
print("(2,4): ",m.reshape(2,4))
print("============================")
print("(4,2): ",m.reshape(4,2))

(2,4):  [[ 3  2  4  7]
 [11  6  7  2]]
(4,2):  [[ 3  2]
 [ 4  7]
 [11  6]
 [ 7  2]]


In [18]:
m

array([[[[[ 3,  2,  4,  7],
          [11,  6,  7,  2]]]]])

In [19]:
import numpy as np
import pandas as pd

In [20]:
ty = pd.read_csv("/content/Retail_Dataset_Modified.csv")
ty

,Store_ID,Store_Name,Brand_Name,Store_Type,City,City_Tier,Product_Name,Category,Sub_Category,Product_Stage,...,Brand_Loyalty,Brand_Awareness,Price_Competitiveness,Weather_Impact,Delivery_Time,Shipping_Cost,Month,Year,Quarter,Season
0,BX_PUNE_034,BrandX_India Superstore Pune,BrandX_India,Flagship,Pune,Tier1,Green Tea 100g,Groceries,Tea,Declining,...,70.8,75.7,Standard,Low,6.0,57,1,2022,Q1,Spring
1,BX_MUMBAI_023,BrandX_India Superstore Mumbai,BrandX_India,Street Store,Mumbai,Metro,White Sugar 1kg,Groceries,Sugar,Declining,...,80.5,81.5,Competitive,Low,4.0,99,1,2022,Q1,Spring
2,BX_PUNE_073,BrandX_India Trends Pune,BrandX_India,Flagship,Pune,Tier1,Levi's T-Shirt,Clothes,T-Shirts,Declining,...,68.5,76.7,Standard,Medium,4.0,101,1,2022,Q1,Spring
3,BX_CHENNAI_061,BrandX_India Trends Chennai,BrandX_India,Mall Store,Chennai,Metro,Adidas Hoodie,Clothes,Jackets,New Launch,...,92.4,88.0,Competitive,Medium,5.0,79,1,2022,Q1,Spring
4,BX_CHENNAI_033,BrandX_India Connect Chennai,BrandX_India,Mall Store,Chennai,Metro,PlayStation 5,Gadgets,Gaming Consoles,Declining,...,82.9,89.5,Competitive,Low,2.0,110,1,2022,Q1,Spring
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5166,BX_JAIPUR_077,BrandX_India Style Jaipur,BrandX_India,Street Store,Jaipur,Tier2,Pepe Jeans,Clothes,Jeans,Declining,...,91.3,68.7,Standard,Medium,3.0,150,11,2024,Q4,Winter
5167,BX_MUMBAI_067,BrandX_India Daily Mumbai,BrandX_India,Express,Mumbai,Metro,White Sugar 1kg,Groceries,Sugar,Growing,...,81.6,82.0,Competitive,Low,7.0,136,7,2023,Q3,Monsoon
5168,BX_KANPUR_097,BrandX_India Gadget Zone Kanpur,BrandX_India,Flagship,Kanpur,Tier2,Dell XPS 13,Electronics,Laptops,Discontinued,...,89.9,68.1,Standard,Low,1.0,222,7,2023,Q3,Monsoon
5169,BX_MUMBAI_031,BrandX_India Style Mumbai,BrandX_India,Street Store,Mumbai,Metro,Nike Air Max,Clothes,Shoes,Mature,...,80.6,86.5,Competitive,Medium,3.0,138,12,2022,Q4,Winter


In [21]:
ty.head()

,Store_ID,Store_Name,Brand_Name,Store_Type,City,City_Tier,Product_Name,Category,Sub_Category,Product_Stage,...,Brand_Loyalty,Brand_Awareness,Price_Competitiveness,Weather_Impact,Delivery_Time,Shipping_Cost,Month,Year,Quarter,Season
0,BX_PUNE_034,BrandX_India Superstore Pune,BrandX_India,Flagship,Pune,Tier1,Green Tea 100g,Groceries,Tea,Declining,...,70.8,75.7,Standard,Low,6.0,57,1,2022,Q1,Spring
1,BX_MUMBAI_023,BrandX_India Superstore Mumbai,BrandX_India,Street Store,Mumbai,Metro,White Sugar 1kg,Groceries,Sugar,Declining,...,80.5,81.5,Competitive,Low,4.0,99,1,2022,Q1,Spring
2,BX_PUNE_073,BrandX_India Trends Pune,BrandX_India,Flagship,Pune,Tier1,Levi's T-Shirt,Clothes,T-Shirts,Declining,...,68.5,76.7,Standard,Medium,4.0,101,1,2022,Q1,Spring
3,BX_CHENNAI_061,BrandX_India Trends Chennai,BrandX_India,Mall Store,Chennai,Metro,Adidas Hoodie,Clothes,Jackets,New Launch,...,92.4,88.0,Competitive,Medium,5.0,79,1,2022,Q1,Spring
4,BX_CHENNAI_033,BrandX_India Connect Chennai,BrandX_India,Mall Store,Chennai,Metro,PlayStation 5,Gadgets,Gaming Consoles,Declining,...,82.9,89.5,Competitive,Low,2.0,110,1,2022,Q1,Spring


In [22]:
ty.tail()

,Store_ID,Store_Name,Brand_Name,Store_Type,City,City_Tier,Product_Name,Category,Sub_Category,Product_Stage,...,Brand_Loyalty,Brand_Awareness,Price_Competitiveness,Weather_Impact,Delivery_Time,Shipping_Cost,Month,Year,Quarter,Season
5166,BX_JAIPUR_077,BrandX_India Style Jaipur,BrandX_India,Street Store,Jaipur,Tier2,Pepe Jeans,Clothes,Jeans,Declining,...,91.3,68.7,Standard,Medium,3.0,150,11,2024,Q4,Winter
5167,BX_MUMBAI_067,BrandX_India Daily Mumbai,BrandX_India,Express,Mumbai,Metro,White Sugar 1kg,Groceries,Sugar,Growing,...,81.6,82.0,Competitive,Low,7.0,136,7,2023,Q3,Monsoon
5168,BX_KANPUR_097,BrandX_India Gadget Zone Kanpur,BrandX_India,Flagship,Kanpur,Tier2,Dell XPS 13,Electronics,Laptops,Discontinued,...,89.9,68.1,Standard,Low,1.0,222,7,2023,Q3,Monsoon
5169,BX_MUMBAI_031,BrandX_India Style Mumbai,BrandX_India,Street Store,Mumbai,Metro,Nike Air Max,Clothes,Shoes,Mature,...,80.6,86.5,Competitive,Medium,3.0,138,12,2022,Q4,Winter
5170,BX_DELHI_032,BrandX_India Electronics Delhi,BrandX_India,Flagship,Delhi,Metro,MacBook Air M2,Electronics,Laptops,Declining,...,91.8,85.0,Competitive,Low,3.0,210,6,2024,Q2,Monsoon


In [24]:
ty.sample(5)

,Store_ID,Store_Name,Brand_Name,Store_Type,City,City_Tier,Product_Name,Category,Sub_Category,Product_Stage,...,Brand_Loyalty,Brand_Awareness,Price_Competitiveness,Weather_Impact,Delivery_Time,Shipping_Cost,Month,Year,Quarter,Season
358,BX_AHMEDABAD_021,BrandX_India Electronics Ahmedabad,BrandX_India,Street Store,Ahmedabad,Tier1,Sony WH-1000XM5,Electronics,Headphones,Growing,...,67.1,77.4,Competitive,Low,6.0,157,3,2022,Q1,Summer
251,BX_MUMBAI_039,BrandX_India Electronics Mumbai,BrandX_India,Express,Mumbai,Metro,HP Pavilion,Electronics,Laptops,New Launch,...,75.3,81.1,Aggressive,Low,1.0,192,2,2022,Q1,Spring
717,BX_JAIPUR_069,BrandX_India Tech Hub Jaipur,BrandX_India,Online Hub,Jaipur,Tier2,Samsung Tab S8,Electronics,Tablets,Declining,...,83.0,62.5,Standard,Low,2.0,234,6,2022,Q2,Monsoon
4038,BX_MUMBAI_038,BrandX_India Accessories Mumbai,BrandX_India,Online Hub,Mumbai,Metro,Sony Alpha a7 IV,Gadgets,Cameras,Mature,...,81.6,83.7,Competitive,Low,3.0,116,5,2024,Q2,Summer
3239,BX_MUMBAI_059,BrandX_India Digital Mumbai,BrandX_India,Online Hub,Mumbai,Metro,iPhone 14,Electronics,Smartphones,Mature,...,90.0,82.0,Competitive,Low,4.0,183,12,2023,Q4,Winter


In [25]:
ty.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5171 entries, 0 to 5170
Data columns (total 47 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   Store_ID               5171 non-null   object 
 1   Store_Name             5171 non-null   object 
 2   Brand_Name             5171 non-null   object 
 3   Store_Type             5171 non-null   object 
 4   City                   5109 non-null   object 
 5   City_Tier              5171 non-null   object 
 6   Product_Name           5098 non-null   object 
 7   Category               5171 non-null   object 
 8   Sub_Category           5171 non-null   object 
 9   Product_Stage          5171 non-null   object 
 10  Quantity_Available     5171 non-null   object 
 11  Units_Sold             5171 non-null   object 
 12  Unit_Price             5171 non-null   int64  
 13  Cost_Price             5171 non-null   int64  
 14  Revenue                5099 non-null   object 
 15  Prof

In [26]:
ty.isnull().sum()

,0
Store_ID,0
Store_Name,0
Brand_Name,0
Store_Type,0
City,62
City_Tier,0
Product_Name,73
Category,0
Sub_Category,0
Product_Stage,0


In [27]:
ty.isnull().sum().sum()

np.int64(412)

In [28]:
ty.head(9)

,Store_ID,Store_Name,Brand_Name,Store_Type,City,City_Tier,Product_Name,Category,Sub_Category,Product_Stage,...,Brand_Loyalty,Brand_Awareness,Price_Competitiveness,Weather_Impact,Delivery_Time,Shipping_Cost,Month,Year,Quarter,Season
0,BX_PUNE_034,BrandX_India Superstore Pune,BrandX_India,Flagship,Pune,Tier1,Green Tea 100g,Groceries,Tea,Declining,...,70.8,75.7,Standard,Low,6.0,57,1,2022,Q1,Spring
1,BX_MUMBAI_023,BrandX_India Superstore Mumbai,BrandX_India,Street Store,Mumbai,Metro,White Sugar 1kg,Groceries,Sugar,Declining,...,80.5,81.5,Competitive,Low,4.0,99,1,2022,Q1,Spring
2,BX_PUNE_073,BrandX_India Trends Pune,BrandX_India,Flagship,Pune,Tier1,Levi's T-Shirt,Clothes,T-Shirts,Declining,...,68.5,76.7,Standard,Medium,4.0,101,1,2022,Q1,Spring
3,BX_CHENNAI_061,BrandX_India Trends Chennai,BrandX_India,Mall Store,Chennai,Metro,Adidas Hoodie,Clothes,Jackets,New Launch,...,92.4,88.0,Competitive,Medium,5.0,79,1,2022,Q1,Spring
4,BX_CHENNAI_033,BrandX_India Connect Chennai,BrandX_India,Mall Store,Chennai,Metro,PlayStation 5,Gadgets,Gaming Consoles,Declining,...,82.9,89.5,Competitive,Low,2.0,110,1,2022,Q1,Spring
5,BX_DELHI_082,BrandX_India Superstore Delhi,BrandX_India,Street Store,Delhi,Metro,Toor Dal 1kg,Groceries,Dal,New Launch,...,81.3,85.3,Aggressive,Low,4.0,108,1,2022,Q1,Spring
6,BX_MUMBAI_062,BrandX_India Accessories Mumbai,BrandX_India,Street Store,Mumbai,Metro,PlayStation 5,Gadgets,Gaming Consoles,Mature,...,98.0,81.6,Competitive,Low,2.0,90,1,2022,Q1,Spring
7,BX_DELHI_062,BrandX_India Digital Delhi,BrandX_India,Mall Store,Delhi,Metro,MacBook Air M2,Electronics,Laptops,Mature,...,81.6,82.4,Competitive,Low,3.0,137,1,2022,Q1,Spring
8,BX_MUMBAI_042,BrandX_India Appliances Mumbai,BrandX_India,Street Store,Mumbai,Metro,NaN,Home Appliances,Water Purifiers,Declining,...,96.3,82.7,Aggressive,Low,4.0,214,1,2022,Q1,Spring


In [29]:
ty.columns

Index(['Store_ID', 'Store_Name', 'Brand_Name', 'Store_Type', 'City',
       'City_Tier', 'Product_Name', 'Category', 'Sub_Category',
       'Product_Stage', 'Quantity_Available', 'Units_Sold', 'Unit_Price',
       'Cost_Price', 'Revenue', 'Profit_Margin', 'Average_Order_Value',
       'Inventory_Turnover', 'Days_of_Stock', 'Customer_Segment',
       'Sales_Channel', 'Payment_Method', 'Supplier', 'Supplier_Rating',
       'Promotion_Type', 'Promotion_Impact', 'Max_Discount_Offered',
       'Return_Rate', 'Return_Reason', 'Customer_Satisfaction',
       'Online_Rating', 'Review_Count', 'Sales_Rep_Experience',
       'Sales_Rep_Rating', 'Market_Share', 'Competition_Level',
       'Competitor_Count', 'Brand_Loyalty', 'Brand_Awareness',
       'Price_Competitiveness', 'Weather_Impact', 'Delivery_Time',
       'Shipping_Cost', 'Month', 'Year', 'Quarter', 'Season'],
      dtype='object')

In [31]:
ty["City"].value_counts()

,count
City,
Delhi,1031
Mumbai,980
Bangalore,512
Chennai,485
Hyderabad,470
Pune,272
Jaipur,268
Ahmedabad,254
Surat,232


In [33]:
ty["City_2"] = ty["City"].replace({"pune" : "Pune"})

In [34]:
ty.columns

Index(['Store_ID', 'Store_Name', 'Brand_Name', 'Store_Type', 'City',
       'City_Tier', 'Product_Name', 'Category', 'Sub_Category',
       'Product_Stage', 'Quantity_Available', 'Units_Sold', 'Unit_Price',
       'Cost_Price', 'Revenue', 'Profit_Margin', 'Average_Order_Value',
       'Inventory_Turnover', 'Days_of_Stock', 'Customer_Segment',
       'Sales_Channel', 'Payment_Method', 'Supplier', 'Supplier_Rating',
       'Promotion_Type', 'Promotion_Impact', 'Max_Discount_Offered',
       'Return_Rate', 'Return_Reason', 'Customer_Satisfaction',
       'Online_Rating', 'Review_Count', 'Sales_Rep_Experience',
       'Sales_Rep_Rating', 'Market_Share', 'Competition_Level',
       'Competitor_Count', 'Brand_Loyalty', 'Brand_Awareness',
       'Price_Competitiveness', 'Weather_Impact', 'Delivery_Time',
       'Shipping_Cost', 'Month', 'Year', 'Quarter', 'Season', 'City_2'],
      dtype='object')

In [38]:
ty["City_2"].value_counts()

,count
City_2,
Delhi,1031
Mumbai,980
Bangalore,512
Chennai,485
Hyderabad,470
Pune,273
Jaipur,268
Ahmedabad,254
Surat,232


In [41]:
ty["City_2"] = ty["City"].replace({"pune" : "Pune" , "KANPUR" : "Kanpur"})

In [42]:
ty["City_2"].value_counts()

,count
City_2,
Delhi,1031
Mumbai,980
Bangalore,512
Chennai,485
Hyderabad,470
Pune,273
Jaipur,268
Ahmedabad,254
Surat,232


In [43]:
for j in ty["City"]:
  print(j)

Pune
Mumbai
Pune
Chennai
Chennai
Delhi
Mumbai
Delhi
Mumbai
Nagpur
Mumbai
Delhi
Delhi
Delhi
Nagpur
Bangalore
Delhi
Bangalore
Hyderabad
Mumbai
Delhi
Mumbai
Mumbai
Pune
Delhi
Chennai
Mumbai
nan
Bhopal
Visakhapatnam
Mumbai
Surat
Jaipur
Mumbai
Mumbai
Ahmedabad
Bangalore
Mumbai
Delhi
Mumbai
Mumbai
Bangalore
Bangalore
Bangalore
Delhi
Mumbai
Surat
Surat
Chennai
Jaipur
Kanpur
Delhi
Mumbai
Delhi
Mumbai
Mumbai
Mumbai
Mumbai
Surat
Mumbai
Visakhapatnam
Hyderabad
Delhi
Surat
Visakhapatnam
Mumbai
Pune
Bhopal
Chennai
Bangalore
Bhopal
Chennai
Ahmedabad
Hyderabad
Delhi
Chennai
Bangalore
Delhi
Hyderabad
Mumbai
Bangalore
Bangalore
Hyderabad
Mumbai
CHENNAI
Delhi
Bangalore
Bangalore
Mumbai
Delhi
Mumbai
Hyderabad
Hyderabad
Visakhapatnam
Mumbai
Mumbai
Bangalore
Chennai
Pune
Bangalore
Mumbai
Jaipur
Mumbai
Delhi
Chennai
Surat
Delhi
Hyderabad
Mumbai
Delhi
Jaipur
Mumbai
Mumbai
Bangalore
Hyderabad
Jaipur
Hyderabad
Mumbai
Delhi
Kanpur
Mumbai
Visakhapatnam
Surat
Ahmedabad
Delhi
Mumbai
Delhi
Chennai
Chennai
Ahmedabad

In [44]:
e = []
for j in ty["City"]:
  if j == "KANPUR" or j == "Kanpur" or j == "kanpur":
    e.append(j)
print(e)

['Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'KANPUR', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur']


In [47]:
e.index("Kanpur")

0

In [45]:
len(e)

99

In [48]:
ty["City"].sort_values()

,City
1957,Chennai
3323,Chennai
913,Chennai
2022,Delhi
658,Delhi
...,...
4882,NaN
4956,NaN
5059,NaN
5068,NaN


In [51]:
ty["City"].where((ty["City"] == "KANPUR") | (ty["City"] == "Kanpur"))

,City
0,NaN
1,NaN
2,NaN
3,NaN
4,NaN
...,...
5166,NaN
5167,NaN
5168,NaN
5169,NaN


In [54]:
ty['City_cleaned'] = ty['City'].str.strip().str.capitalize()
ty_kanpur = ty[ty['City_cleaned'] == 'Kanpur']
ty_kanpur

,Store_ID,Store_Name,Brand_Name,Store_Type,City,City_Tier,Product_Name,Category,Sub_Category,Product_Stage,...,Price_Competitiveness,Weather_Impact,Delivery_Time,Shipping_Cost,Month,Year,Quarter,Season,City_2,City_cleaned
50,BX_KANPUR_045,BrandX_India Tech Hub Kanpur,BrandX_India,Flagship,Kanpur,Tier2,iPad Pro,Electronics,Tablets,Mature,...,Standard,Low,1.0,276,1,2022,Q1,Spring,Kanpur,Kanpur
119,BX_KANPUR_004,BrandX_India Apparel Kanpur,BrandX_India,Flagship,Kanpur,Tier2,Levi's 511 Jeans,Clothes,Jeans,Discontinued,...,Standard,Medium,7.0,102,1,2022,Q1,Spring,Kanpur,Kanpur
147,BX_KANPUR_019,BrandX_India Superstore Kanpur,BrandX_India,Online Hub,Kanpur,Tier2,Tata Tea Premium,Groceries,Tea,New Launch,...,Standard,Low,2.0,51,2,2022,Q1,Spring,Kanpur,Kanpur
211,BX_KANPUR_059,BrandX_India Comfort Kanpur,BrandX_India,Express,Kanpur,Tier2,Samsung 23L Solo,Home Appliances,Microwaves,Growing,...,Standard,Low,2.0,739,2,2022,Q1,Spring,Kanpur,Kanpur
273,BX_KANPUR_069,BrandX_India Accessories Kanpur,BrandX_India,Flagship,Kanpur,Tier2,PlayStation 5,Gadgets,Gaming Consoles,Declining,...,Standard,Low,2.0,115,3,2022,Q1,Summer,Kanpur,Kanpur
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4946,BX_KANPUR_055,BrandX_India Living Kanpur,BrandX_India,Online Hub,Kanpur,Tier2,Bosch 6kg Top Load,Home Appliances,Washing Machines,Discontinued,...,Standard,Low,3.0,455,11,2024,Q4,Winter,Kanpur,Kanpur
5017,BX_KANPUR_055,BrandX_India Electronics Kanpur,BrandX_India,Express,Kanpur,Tier2,iPad Pro,Electronics,Tablets,Growing,...,Standard,Low,7.0,268,12,2024,Q4,Winter,Kanpur,Kanpur
5066,BX_KANPUR_038,BrandX_India Express Kanpur,BrandX_India,Online Hub,Kanpur,Tier2,Tata Tea Premium,Groceries,Tea,Declining,...,Standard,Low,3.0,100,12,2024,Q4,Winter,Kanpur,Kanpur
5163,BX_KANPUR_030,BrandX_India Digital Kanpur,BrandX_India,Mall Store,KANPUR,Tier2,iPhone 14,Electronics,Smartphones,Discontinued,...,Standard,Low,2.0,242,10,2022,Q4,Winter,KANPUR,Kanpur


In [55]:
ty.head(9)

,Store_ID,Store_Name,Brand_Name,Store_Type,City,City_Tier,Product_Name,Category,Sub_Category,Product_Stage,...,Price_Competitiveness,Weather_Impact,Delivery_Time,Shipping_Cost,Month,Year,Quarter,Season,City_2,City_cleaned
0,BX_PUNE_034,BrandX_India Superstore Pune,BrandX_India,Flagship,Pune,Tier1,Green Tea 100g,Groceries,Tea,Declining,...,Standard,Low,6.0,57,1,2022,Q1,Spring,Pune,Pune
1,BX_MUMBAI_023,BrandX_India Superstore Mumbai,BrandX_India,Street Store,Mumbai,Metro,White Sugar 1kg,Groceries,Sugar,Declining,...,Competitive,Low,4.0,99,1,2022,Q1,Spring,Mumbai,Mumbai
2,BX_PUNE_073,BrandX_India Trends Pune,BrandX_India,Flagship,Pune,Tier1,Levi's T-Shirt,Clothes,T-Shirts,Declining,...,Standard,Medium,4.0,101,1,2022,Q1,Spring,Pune,Pune
3,BX_CHENNAI_061,BrandX_India Trends Chennai,BrandX_India,Mall Store,Chennai,Metro,Adidas Hoodie,Clothes,Jackets,New Launch,...,Competitive,Medium,5.0,79,1,2022,Q1,Spring,Chennai,Chennai
4,BX_CHENNAI_033,BrandX_India Connect Chennai,BrandX_India,Mall Store,Chennai,Metro,PlayStation 5,Gadgets,Gaming Consoles,Declining,...,Competitive,Low,2.0,110,1,2022,Q1,Spring,Chennai,Chennai
5,BX_DELHI_082,BrandX_India Superstore Delhi,BrandX_India,Street Store,Delhi,Metro,Toor Dal 1kg,Groceries,Dal,New Launch,...,Aggressive,Low,4.0,108,1,2022,Q1,Spring,Delhi,Delhi
6,BX_MUMBAI_062,BrandX_India Accessories Mumbai,BrandX_India,Street Store,Mumbai,Metro,PlayStation 5,Gadgets,Gaming Consoles,Mature,...,Competitive,Low,2.0,90,1,2022,Q1,Spring,Mumbai,Mumbai
7,BX_DELHI_062,BrandX_India Digital Delhi,BrandX_India,Mall Store,Delhi,Metro,MacBook Air M2,Electronics,Laptops,Mature,...,Competitive,Low,3.0,137,1,2022,Q1,Spring,Delhi,Delhi
8,BX_MUMBAI_042,BrandX_India Appliances Mumbai,BrandX_India,Street Store,Mumbai,Metro,NaN,Home Appliances,Water Purifiers,Declining,...,Aggressive,Low,4.0,214,1,2022,Q1,Spring,Mumbai,Mumbai


In [58]:
ty[ty["Store_Type"] == "Flagship"]

,Store_ID,Store_Name,Brand_Name,Store_Type,City,City_Tier,Product_Name,Category,Sub_Category,Product_Stage,...,Price_Competitiveness,Weather_Impact,Delivery_Time,Shipping_Cost,Month,Year,Quarter,Season,City_2,City_cleaned
0,BX_PUNE_034,BrandX_India Superstore Pune,BrandX_India,Flagship,Pune,Tier1,Green Tea 100g,Groceries,Tea,Declining,...,Standard,Low,6.0,57,1,2022,Q1,Spring,Pune,Pune
2,BX_PUNE_073,BrandX_India Trends Pune,BrandX_India,Flagship,Pune,Tier1,Levi's T-Shirt,Clothes,T-Shirts,Declining,...,Standard,Medium,4.0,101,1,2022,Q1,Spring,Pune,Pune
21,BX_MUMBAI_088,BrandX_India Express Mumbai,BrandX_India,Flagship,Mumbai,Metro,Basmati Rice 5kg,Groceries,Rice,Growing,...,Aggressive,Low,6.0,143,1,2022,Q1,Spring,Mumbai,Mumbai
23,BX_PUNE_051,BrandX_India Fashion Pune,BrandX_India,Flagship,Pune,Tier1,Nike Air Max,Clothes,Shoes,Discontinued,...,Competitive,Medium,3.0,121,1,2022,Q1,Spring,Pune,Pune
24,BX_DELHI_061,BrandX_India Home Delhi,BrandX_India,Flagship,Delhi,Metro,IFB 7kg Front Load,Home Appliances,Washing Machines,Declining,...,Aggressive,Low,7.0,665,1,2022,Q1,Spring,Delhi,Delhi
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5149,BX_DELHI_054,BrandX_India Style Delhi,BrandX_India,Flagship,Delhi,Metro,Nike Jacket,Clothes,Jackets,Declining,...,Aggressive,Medium,1.0,65,12,2023,Q4,Winter,Delhi,Delhi
5160,BX_MUMBAI_019,BrandX_India Superstore Mumbai,BrandX_India,Flagship,Mumbai,Metro,Sunflower Oil 1L,Groceries,Oil,Growing,...,Aggressive,Low,1.0,147,10,2024,Q4,Winter,Mumbai,Mumbai
5161,BX_JAIPUR_075,BrandX_India Fashion Jaipur,BrandX_India,Flagship,Jaipur,Tier2,Adidas Hoodie,Clothes,Jackets,Mature,...,Standard,Medium,5.0,98,12,2023,Q4,Winter,Jaipur,Jaipur
5168,BX_KANPUR_097,BrandX_India Gadget Zone Kanpur,BrandX_India,Flagship,Kanpur,Tier2,Dell XPS 13,Electronics,Laptops,Discontinued,...,Standard,Low,1.0,222,7,2023,Q3,Monsoon,Kanpur,Kanpur


In [59]:
len(ty[ty["Store_Type"] == "Flagship"])

1055

In [60]:
ty[(ty["Store_Type"] == "Flagship") & (ty["City"] == "Mumbai")]

,Store_ID,Store_Name,Brand_Name,Store_Type,City,City_Tier,Product_Name,Category,Sub_Category,Product_Stage,...,Price_Competitiveness,Weather_Impact,Delivery_Time,Shipping_Cost,Month,Year,Quarter,Season,City_2,City_cleaned
21,BX_MUMBAI_088,BrandX_India Express Mumbai,BrandX_India,Flagship,Mumbai,Metro,Basmati Rice 5kg,Groceries,Rice,Growing,...,Aggressive,Low,6.0,143,1,2022,Q1,Spring,Mumbai,Mumbai
26,BX_MUMBAI_019,BrandX_India Mobile Mumbai,BrandX_India,Flagship,Mumbai,Metro,Sony Alpha a7 IV,Gadgets,Cameras,Mature,...,Aggressive,Low,4.0,131,1,2022,Q1,Spring,Mumbai,Mumbai
30,BX_MUMBAI_020,BrandX_India Tech Hub Mumbai,BrandX_India,Flagship,Mumbai,Metro,Sony Bravia 43Inch,Electronics,Smart TVs,Growing,...,Competitive,Low,4.0,209,1,2022,Q1,Spring,Mumbai,Mumbai
37,BX_MUMBAI_092,BrandX_India Accessories Mumbai,BrandX_India,Flagship,Mumbai,Metro,Canon EOS R6,Gadgets,Cameras,New Launch,...,Aggressive,Low,3.0,123,1,2022,Q1,Spring,Mumbai,Mumbai
39,BX_MUMBAI_068,BrandX_India Electronics Mumbai,BrandX_India,Flagship,Mumbai,Metro,Samsung Galaxy S23,Electronics,Smartphones,Declining,...,Competitive,Low,2.0,277,1,2022,Q1,Spring,Mumbai,Mumbai
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5034,BX_MUMBAI_041,BrandX_India Gadget Zone Mumbai,BrandX_India,Flagship,Mumbai,Metro,OnePlus 11,Electronics,Smartphones,Declining,...,Competitive,Low,2.0,219,12,2024,Q4,Winter,Mumbai,Mumbai
5106,BX_MUMBAI_033,BrandX_India Trends Mumbai,BrandX_India,Flagship,Mumbai,Metro,H&M Cotton Tee,Clothes,T-Shirts,Growing,...,Competitive,Medium,6.0,142,12,2024,Q4,Winter,Mumbai,Mumbai
5113,BX_MUMBAI_003,BrandX_India Connect Mumbai,BrandX_India,Flagship,Mumbai,Metro,Mi Power Bank,Gadgets,Power Banks,Discontinued,...,Aggressive,Low,5.0,114,12,2024,Q4,Winter,Mumbai,Mumbai
5126,BX_MUMBAI_086,BrandX_India Fresh Mumbai,BrandX_India,Flagship,Mumbai,Metro,Sunflower Oil 1L,Groceries,Oil,Mature,...,Aggressive,Low,2.0,145,8,2024,Q3,Monsoon,Mumbai,Mumbai


In [61]:
ty

,Store_ID,Store_Name,Brand_Name,Store_Type,City,City_Tier,Product_Name,Category,Sub_Category,Product_Stage,...,Price_Competitiveness,Weather_Impact,Delivery_Time,Shipping_Cost,Month,Year,Quarter,Season,City_2,City_cleaned
0,BX_PUNE_034,BrandX_India Superstore Pune,BrandX_India,Flagship,Pune,Tier1,Green Tea 100g,Groceries,Tea,Declining,...,Standard,Low,6.0,57,1,2022,Q1,Spring,Pune,Pune
1,BX_MUMBAI_023,BrandX_India Superstore Mumbai,BrandX_India,Street Store,Mumbai,Metro,White Sugar 1kg,Groceries,Sugar,Declining,...,Competitive,Low,4.0,99,1,2022,Q1,Spring,Mumbai,Mumbai
2,BX_PUNE_073,BrandX_India Trends Pune,BrandX_India,Flagship,Pune,Tier1,Levi's T-Shirt,Clothes,T-Shirts,Declining,...,Standard,Medium,4.0,101,1,2022,Q1,Spring,Pune,Pune
3,BX_CHENNAI_061,BrandX_India Trends Chennai,BrandX_India,Mall Store,Chennai,Metro,Adidas Hoodie,Clothes,Jackets,New Launch,...,Competitive,Medium,5.0,79,1,2022,Q1,Spring,Chennai,Chennai
4,BX_CHENNAI_033,BrandX_India Connect Chennai,BrandX_India,Mall Store,Chennai,Metro,PlayStation 5,Gadgets,Gaming Consoles,Declining,...,Competitive,Low,2.0,110,1,2022,Q1,Spring,Chennai,Chennai
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5166,BX_JAIPUR_077,BrandX_India Style Jaipur,BrandX_India,Street Store,Jaipur,Tier2,Pepe Jeans,Clothes,Jeans,Declining,...,Standard,Medium,3.0,150,11,2024,Q4,Winter,Jaipur,Jaipur
5167,BX_MUMBAI_067,BrandX_India Daily Mumbai,BrandX_India,Express,Mumbai,Metro,White Sugar 1kg,Groceries,Sugar,Growing,...,Competitive,Low,7.0,136,7,2023,Q3,Monsoon,Mumbai,Mumbai
5168,BX_KANPUR_097,BrandX_India Gadget Zone Kanpur,BrandX_India,Flagship,Kanpur,Tier2,Dell XPS 13,Electronics,Laptops,Discontinued,...,Standard,Low,1.0,222,7,2023,Q3,Monsoon,Kanpur,Kanpur
5169,BX_MUMBAI_031,BrandX_India Style Mumbai,BrandX_India,Street Store,Mumbai,Metro,Nike Air Max,Clothes,Shoes,Mature,...,Competitive,Medium,3.0,138,12,2022,Q4,Winter,Mumbai,Mumbai


In [63]:
ty[ty.duplicated()]

,Store_ID,Store_Name,Brand_Name,Store_Type,City,City_Tier,Product_Name,Category,Sub_Category,Product_Stage,...,Price_Competitiveness,Weather_Impact,Delivery_Time,Shipping_Cost,Month,Year,Quarter,Season,City_2,City_cleaned
5121,BX_BANGALORE_099,BrandX_India Apparel Bangalore,BrandX_India,Mall Store,Bangalore,Metro,H&M Cotton Tee,Clothes,T-Shirts,Declining,...,Aggressive,Medium,7.0,50,8,2023,Q3,Monsoon,Bangalore,Bangalore
5122,BX_MUMBAI_095,BrandX_India Trends Mumbai,BrandX_India,Mall Store,Mumbai,Metro,Adidas Ultraboost,Clothes,Shoes,Discontinued,...,Competitive,Medium,2.0,75,1,2022,Q1,Spring,Mumbai,Mumbai
5123,BX_BANGALORE_058,BrandX_India Digital Bangalore,BrandX_India,Street Store,Bangalore,Metro,iPad Pro,Electronics,Tablets,Mature,...,Aggressive,Low,2.0,257,6,2022,Q2,Monsoon,Bangalore,Bangalore
5124,BX_DELHI_027,BrandX_India Trends Delhi,BrandX_India,Online Hub,Delhi,Metro,Pepe Jeans,Clothes,Jeans,Growing,...,Aggressive,Medium,3.0,86,12,2024,Q4,Winter,Delhi,Delhi
5125,BX_BANGALORE_062,BrandX_India Daily Bangalore,BrandX_India,Street Store,Bangalore,Metro,Tata Tea Premium,Groceries,Tea,Declining,...,Aggressive,Low,5.0,98,4,2024,Q2,Summer,Bangalore,Bangalore
5126,BX_MUMBAI_086,BrandX_India Fresh Mumbai,BrandX_India,Flagship,Mumbai,Metro,Sunflower Oil 1L,Groceries,Oil,Mature,...,Aggressive,Low,2.0,145,8,2024,Q3,Monsoon,Mumbai,Mumbai
5127,BX_BANGALORE_097,BrandX_India Superstore Bangalore,BrandX_India,Mall Store,Bangalore,Metro,Brown Sugar 500g,Groceries,Sugar,Discontinued,...,Aggressive,Low,4.0,115,5,2022,Q2,Summer,Bangalore,Bangalore
5128,BX_CHENNAI_053,BrandX_India Daily Chennai,BrandX_India,Mall Store,Chennai,Metro,White Sugar 1kg,Groceries,Sugar,Discontinued,...,Aggressive,Low,6.0,136,1,2023,Q1,Spring,Chennai,Chennai
5129,BX_BANGALORE_082,BrandX_India Accessories Bangalore,BrandX_India,Online Hub,Bangalore,Metro,JBL Charge 5,Gadgets,Bluetooth Speakers,Discontinued,...,Competitive,Low,5.0,67,5,2023,Q2,Summer,Bangalore,Bangalore
5130,BX_DELHI_079,BrandX_India Smart Delhi,BrandX_India,Flagship,Delhi,Metro,PlayStation 5,Gadgets,Gaming Consoles,Discontinued,...,Aggressive,Low,1.0,53,10,2022,Q4,Winter,Delhi,Delhi


In [65]:
ty[ty["City_Tier"].duplicated()]

,Store_ID,Store_Name,Brand_Name,Store_Type,City,City_Tier,Product_Name,Category,Sub_Category,Product_Stage,...,Price_Competitiveness,Weather_Impact,Delivery_Time,Shipping_Cost,Month,Year,Quarter,Season,City_2,City_cleaned
2,BX_PUNE_073,BrandX_India Trends Pune,BrandX_India,Flagship,Pune,Tier1,Levi's T-Shirt,Clothes,T-Shirts,Declining,...,Standard,Medium,4.0,101,1,2022,Q1,Spring,Pune,Pune
3,BX_CHENNAI_061,BrandX_India Trends Chennai,BrandX_India,Mall Store,Chennai,Metro,Adidas Hoodie,Clothes,Jackets,New Launch,...,Competitive,Medium,5.0,79,1,2022,Q1,Spring,Chennai,Chennai
4,BX_CHENNAI_033,BrandX_India Connect Chennai,BrandX_India,Mall Store,Chennai,Metro,PlayStation 5,Gadgets,Gaming Consoles,Declining,...,Competitive,Low,2.0,110,1,2022,Q1,Spring,Chennai,Chennai
5,BX_DELHI_082,BrandX_India Superstore Delhi,BrandX_India,Street Store,Delhi,Metro,Toor Dal 1kg,Groceries,Dal,New Launch,...,Aggressive,Low,4.0,108,1,2022,Q1,Spring,Delhi,Delhi
6,BX_MUMBAI_062,BrandX_India Accessories Mumbai,BrandX_India,Street Store,Mumbai,Metro,PlayStation 5,Gadgets,Gaming Consoles,Mature,...,Competitive,Low,2.0,90,1,2022,Q1,Spring,Mumbai,Mumbai
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5166,BX_JAIPUR_077,BrandX_India Style Jaipur,BrandX_India,Street Store,Jaipur,Tier2,Pepe Jeans,Clothes,Jeans,Declining,...,Standard,Medium,3.0,150,11,2024,Q4,Winter,Jaipur,Jaipur
5167,BX_MUMBAI_067,BrandX_India Daily Mumbai,BrandX_India,Express,Mumbai,Metro,White Sugar 1kg,Groceries,Sugar,Growing,...,Competitive,Low,7.0,136,7,2023,Q3,Monsoon,Mumbai,Mumbai
5168,BX_KANPUR_097,BrandX_India Gadget Zone Kanpur,BrandX_India,Flagship,Kanpur,Tier2,Dell XPS 13,Electronics,Laptops,Discontinued,...,Standard,Low,1.0,222,7,2023,Q3,Monsoon,Kanpur,Kanpur
5169,BX_MUMBAI_031,BrandX_India Style Mumbai,BrandX_India,Street Store,Mumbai,Metro,Nike Air Max,Clothes,Shoes,Mature,...,Competitive,Medium,3.0,138,12,2022,Q4,Winter,Mumbai,Mumbai
